
const mongoose = require('mongoose')


const quoteSchema = mongoose.Schema({
    contactId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Contact'
    },  
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    },
    name:String,
    testimonialPAYOrN:Boolean,
    testimonialPRYOrN:Boolean,
    testimonialTYOrN:Boolean,
    testimonialIYOrN:Boolean,
    OP1YOrN:Boolean,
    OP2YOrN:Boolean,
    OP3YOrN:Boolean,
    OP4YOrN:Boolean,
    imageYOrN:Boolean,
    aboutUsTitleYOrN:Boolean,
    aboutUsContainYOrN:Boolean,
    titleYOrN:Boolean,
    contactDetailsYOrN:Boolean,
    logo:String,
    LogoYOrN:Boolean,
    logoCNYOrN:Boolean,
    logoCompanyName:String,
    logoBorderRadiusLogo:String,
    logoBorderRadiusLogo1:String,
    logoBorderRadiusLogo2:String,
    logoBorderRadiusLogo3:String,
    logoBorderRadiusLogo4:String,
    logoWidth:String,
    logoHeight:String,
    logoBackgroundOnlyPng:String,
    logoSelectRadiuseView:String,
    contactDetailsTo:String,
    contactDetailsFrom:String,
    contactDetailsProposalName:String,
    contactDetailsFont:String,
    contactDetailsTextWeight:String,
    contactDetailsTextsize:String,
    contactDetailsAlignment:String,
    contactDetailsWidthText:String,
    contactDetailsLineHeight:String,
    contactDetailsColorText:String,
    titleTextTitle:String,
    titleFont:String,
    titleTextWeight:String,
    titleTextSize:String,
    titleAlignment:String,
    titleWidthText:String,
    titleLineHeight:String,
    titleColorText:String,
    aboutUsTitle:String,
    aboutUsTitleStyle:String,
    aboutUsAboutUs:String,
    aboutUsTextTitle:String,
    aboutUsFont:String,
    aboutUsTextWeight:String,
    aboutUsTextSize:String,
    aboutUsAlignment:String,
    aboutUsWidthText:String,
    aboutUsLineHeight:String,
    aboutUsColorText:String,
    imageImage:String,
    imageBackgroundOnlyPng:String,
    imageRectanglesWidth:String,
    imageRectanglesHeight:String,
    imageBorderRadiusRectangles:String,
    imageRectanglesColor:String,
    ourProductsDetailsTitle:String,
    ourProductsDetailsTitleColor:String,
    ourProductsDetailsIcon01:String,
    ourProductsDetailsTitle01:String,
    ourProductsDetailsText01:String,
    ourProductsDetailsIcon02:String,
    ourProductsDetailsTitle02:String,
    ourProductsDetailsText02:String,
    ourProductsDetailsIcon03:String,
    ourProductsDetailsTitle03:String,
    ourProductsDetailsText03:String,
    ourProductsDetailsIcon04:String,
    ourProductsDetailsTitle04:String,
    ourProductsDetailsText04:String,
    ourProductsTitleStyleColorText:String,
    ourProductsTitleStyleFont:String,
    ourProductsTitleStyleTextWeight:String,
    ourProductsTitleStyleTextSize:String,
    ourProductsTitleStyleAlignment:String,
    ourProductsTitleStyleWidthText:String,
    ourProductsTitleStyleLineHeight:String,
    ourProductsParagraphStyleColorText:String,
    ourProductsParagraphStyleFont:String,
    ourProductsParagraphStyleTextWeight:String,
    ourProductsParagraphStyleTextSize:String,
    ourProductsParagraphStyleAlignment:String,
    ourProductsParagraphStyleWidthText:String,
    ourProductsParagraphStyleLineHeight:String,
    testimonialImage:String,
    testimonialBorderRadiusLogo:String,
    testimonialNameTitle:String,
    testimonialNameTitleColor:String,
    testimonialProfession:String,
    testimonialProfessionColor:String,
    testimonialParagraph:String,
    testimonialBackgroundColor:String,
    timesAndPricesImage:String,
    timesAndPricesBorderRadiusLogo:String,
    timesAndPricesParagraph:String,
    timesAndPricesTextColor:String,
    timesAndPricesEstimatedDate:String,
    timesAndPricesTotal:String,
    timesAndPricesVAT:String,
    timesAndPricesCoin:String,
    timesAndPricesAddNote:String,
    timesAndPricesColorText:String,
    companyDetailsTitleCall:String,
    companyDetailsCall:String,
    companyDetailsTitleMail:String,
    companyDetailsMail:String,
    companyDetailsTitleWebsite:String,
    companyDetailsWebsite:String,
    createdDate: { type: Date, default: Date.now }

})


module.exports = mongoose.model('Quote', quoteSchema)